=== pyramation/cosmology/packages/cosmos-registry/chain-registry/chain.schema.json
{
    "$id": "https://sikka.tech/chain.schema.json",
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "Cosmos Chain",
    "description": "Cosmos Chain.json is a metadata file that contains information about a cosmos sdk based chain.",
    "type": "object",
    "required": [
        "chain_name",
        "chain_id",
        "bech32_prefix"
    ],
    "properties": {
        "chain_name": {
            "type": "string"
        },
        "chain_id": {
            "type": "string"
        },
        "pretty_name": {
            "type": "string"
        },
        "status": {
            "enum": [
                "live",
                "upcoming",
                "killed"
            ]
        },
        "network_type": {
            "enum": [
                "mainnet",
                "testnet"
            ]
        },
        "bech32_prefix": {
            "type": "string"
        },
        "genesis": {
            "type": "object",
            "properties": {
                "genesis_url": {
                    "type": "string"
                }
            }
        },
        "daemon_name": {
            "type": "string"
        },
        "node_home": {
            "type": "string"
        },
        "key_algos": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "secp256k1",
                    "ethsecp256k1",
                    "ed25519",
                    "sr25519"
                ],
                "uniqueItems": true
            }
        },
        "slip44": {
            "type": "number"
        },
        "fees": {
            "type": "object",
            "properties": {
                "fee_tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/fee_token"
                    }
                }
            }
        },
        "codebase": {
            "type": "object",
            "required": [
                "git_repo",
                "recommended_version",
                "compatible_versions"
            ],
            "properties": {
                "git_repo": {
                    "type": "string",
                    "format": "uri"
                },
                "recommended_version": {
                    "type": "string"
                },
                "compatible_versions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "binaries": {
                    "type": "object",
                    "properties": {
                        "linux/amd": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                }
            }
        },
        "peers": {
            "type": "object",
            "properties": {
                "seeds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                },
                "persistent_peers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                }
            }
        },
        "apis": {
            "type": "object",
            "properties": {
                "rpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "rest": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "grpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                }
            }
        },
        "explorers": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/explorer"
            }
        }
    },
    "$defs": {
        "peer": {
            "type": "object",
            "required": [
                "id",
                "address"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "endpoint": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "explorer": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "tx_page": {
                    "type": "string"
                }
            }
        },
        "fee_token": {
            "type": "object",
            "required": [
                "denom"
            ],
            "properties": {
                "denom": {
                    "type": "string"
                },
                "fixed_min_gas_price": {
                    "type": "number"
                }
            }
        }
    }
}

=== pyramation/cosmology/packages/registry/chain-registry/evmos/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "evmos",
  "status": "live",
  "network_type": "mainnet",
  "pretty_name": "Evmos",
  "chain_id": "evmos_9001-1",
  "bech32_prefix": "evmos",
  "node_home": "$HOME/.evmosd",
  "genesis": {
    "genesis_url": "https://archive.evmos.dev/genesis/genesis.json"
  },
  "slip44": 60,
  "fees": {
    "fee_tokens": [
      {
        "denom": "aevmos"
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/tharsis/evmos",
    "recommended_version": "v1.1.0",
    "compatible_versions": [
      "v1.1.0"
    ],
    "binaries": {
      "linux/amd64": "https://github.com/tharsis/evmos/releases/download/v1.1.0/evmos_1.1.0_Linux_x86_64.tar.gz",
      "linux/arm64": "https://github.com/tharsis/evmos/releases/download/v1.1.0/evmos_1.1.0_Linux_arm64.tar.gz",
      "darwin/amd64": "https://github.com/tharsis/evmos/releases/download/v1.1.0/evmos_1.1.0_Darwin_x86_64.tar.gz",
      "darwin/arm64": "https://github.com/tharsis/evmos/releases/download/v1.1.0/evmos_1.1.0_Darwin_arm64.tar.gz",
      "windows/amd64": "https://github.com/tharsis/evmos/releases/download/v1.1.0/evmos_1.1.0_Windows_x86_64.zip"
    }
  },
  "peers": {
    "seeds": [
      {
        "id": "906840c2f447915f3d0e37bc68221f5494f541db",
        "address": "3.39.58.32:26656",
        "provider": "Cosmostation"
      },
      {
        "id": "7aa31684d201f8ebc0b1e832d90d7490345d77ee",
        "address": "52.10.99.253:26656",
        "provider": "Cosmostation"
      },
      {
        "id": "5740e4a36e646e80cc5648daf5e983e5b5d8f265",
        "address": "54.39.18.27:26656",
        "provider": "Figment"
      },
      {
        "id": "de2c5e946e21360d4ffa3885579fa038a7d9776e",
        "address": "46.101.148.190:26656",
        "provider": "DragonStake"
      },
      {
        "id": "588cedb70fa1d98c14a2f2c1456bfa41e1a156a8",
        "address": "evmos-sentry.mercury-nodes.net:29539",
        "provider": "Mercury"
      }
    ],
    "persistent_peers": [
      {
        "id": "906840c2f447915f3d0e37bc68221f5494f541db",
        "address": "3.39.58.32:26656",
        "provider": "Cosmostation"
      },
      {
        "id": "7aa31684d201f8ebc0b1e832d90d7490345d77ee",
        "address": "52.10.99.253:26656",
        "provider": "Cosmostation"
      },
      {
        "id": "5740e4a36e646e80cc5648daf5e983e5b5d8f265",
        "address": "54.39.18.27:26656",
        "provider": "Figment"
      },
      {
        "id": "de2c5e946e21360d4ffa3885579fa038a7d9776e",
        "address": "46.101.148.190:26656",
        "provider": "DragonStake"
      },
      {
        "id": "588cedb70fa1d98c14a2f2c1456bfa41e1a156a8",
        "address": "evmos-sentry.mercury-nodes.net:29539",
        "provider": "Mercury"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://tendermint.bd.evmos.org:26657",
        "provider": "evmos.org"
      }
    ],
    "rest": [
      {
        "address": "https://rest.bd.evmos.org:1317",
        "provider": "evmos.org"
      }
    ],
    "grpc": [
      {
        "address": "https://grpc.bd.evmos.org:9090",
        "provider": "evmos.org"
      }
    ],
    "evm-http-jsonrpc": [
      {
        "address": "https://eth.bd.evmos.org:8545",
        "provider": "evmos.org"
      }
    ]
  },
  "explorers": [
    {
      "kind": "mintscan",
      "url": "https://www.mintscan.io/evmos",
      "tx_page": "https://www.mintscan.io/evmos/txs/${txHash}"
    },
    {
      "kind": "bigdipper",
      "url": "https://evmos.bigdipper.live",
      "tx_page": "https://evmos.bigdipper.live/transactions/${txHash}"
    },
    {
      "kind": "blockscout",
      "url": "https://evm.evmos.org",
      "tx_page": "https://evm.evmos.org/tx/${txHash}"
    },
    {
        "kind": "ping-pub",
        "url": "https://ping.pub/evmos",
        "tx_page": "https://ping.pub/evmos/tx/${txHash}"
    }
  ]
}

=== pyramation/cosmology/packages/cosmos-registry/chain-registry/fetchhub/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "fetchhub",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Fetch Hub",
    "chain_id": "fetchhub-2",
    "bech32_prefix": "fetch",
    "daemon_name": "fetchd",
    "node_home": "$HOME/.fetchd",
    "genesis": {
        "genesis_url": "https://raw.githubusercontent.com/fetchai/genesis-fetchhub/14c62009a35486b233fcb3de48f3dcd006dab240/data/genesis.json"
    },
    "slip44": 118,
    "codebase": {
        "git_repo": "https://github.com/fetchai/fetchd",
        "recommended_version": "v0.8.7",
        "compatible_versions": [
            "v0.8.7"
        ]
    },
    "peers": {
        "seeds": [
            {
                "id": "c240ca38b990a7d3f25621eb848d0222d5b50278",
                "address": "connect-fetchhub.fetch.ai:36656",
                "provider": "fetch.ai"
            },
            {
                "id": "3e19e092c5ddd19a6aa8ba87fa8a37566d4f7f38",
                "address": "connect-fetchhub.fetch.ai:36657",
                "provider": "fetch.ai"
            },
            {
                "id": "b75b1ed0a1257e99d41b48d0704a605854d80514",
                "address": "connect-fetchhub.fetch.ai:36658",
                "provider": "fetch.ai"
            }
        ],
        "persistent_peers": [
            {
                "id": "d70030b25de2317e7d6bad482d4cb186c72a5e39",
                "address": "sentries-fetchhub.fetch.ai:36600",
                "provider": "fetch.ai"
            },
            {
                "id": "42f2879b8feec50937234a20a54a87d5c350d680",
                "address": "sentries-fetchhub.fetch.ai:36601",
                "provider": "fetch.ai"
            },
            {
                "id": "56f1049931e9ce9777180460fed912b708205ed5",
                "address": "sentries-fetchhub.fetch.ai:36602",
                "provider": "fetch.ai"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://rpc-fetchhub.fetch.ai:443",
                "provider": "fetch.ai"
            }
        ],
        "rest": [
            {
                "address": "https://rest-fetchhub.fetch.ai",
                "provider": "fetch.ai"
            }
        ],
        "grpc": [
            {
                "address": "https://grpc-fetchhub.fetch.ai:443",
                "provider": "fetch.ai"
            }
        ]
    },
    "explorers": [
        {
            "kind": "mintscan",
            "url": "https://www.mintscan.io/fetchai",
            "tx_page": "https://www.mintscan.io/fetchai/txs/${txHash}"
        },
        {
            "kind": "bigdipper",
            "url": "https://explore-fetchhub.fetch.ai",
            "tx_page": "https://explore-fetchhub.fetch.ai/transactions/${txHash}"
        }
    ]
}

=== pyramation/cosmology/packages/registry/chain-registry/dig/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "dig",
  "status": "live",
  "network_type": "mainnet",
  "pretty_name": "Dig Chain",
  "chain_id": "dig-1",
  "bech32_prefix": "dig",
  "daemon_name": "digd",
  "node_home": "$HOME/.dig",
  "genesis": {
    "genesis_url": "https://raw.githubusercontent.com/notional-labs/dig/master/networks/mainnets/dig-1/genesis.json"
  },
  "key_algos": ["secp256k1", "ethsecp256k1"],
  "slip44": 118,
  "fees": {
    "fee_tokens": [
      {
        "denom": "udig"
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/notional-labs/dig",
    "recommended_version": "v1.0.0",
    "compatible_versions": ["v1.0.0"]
  },
  "peers": {
    "seeds": [
      {
        "id": "37b2839da4463b22a51b1fe20d97992164270eba",
        "address": "62.171.157.192:26656"
      },
      {
        "id": "e2c96b96d4c3a461fb246edac3b3cdbf47768838",
        "address": "65.21.202.37:6969"
      }
    ],
    "persistent_peers": [
      {
        "id": "33f4788e1c6a378b929c66f31e8d253b9fd47c47",
        "address": "194.163.154.251:26656"
      },
      {
        "id": "64eccffdc60a206227032d3a021fbf9dfc686a17",
        "address": "194.163.156.84:26656"
      },
      {
        "id": "be7598b2d56fb42a27821259ad14aff24c40f3d2",
        "address": "172.16.152.118:26656"
      },
      {
        "id": "f446e37e47297ce9f8951957d17a2ae9a16db0b8",
        "address": "137.184.67.162:26656"
      },
      {
        "id": "ab2fa2789f481e2856a5d83a2c3028c5b215421d",
        "address": "144.91.117.49:26656"
      },
      {
        "id": "e9e89250b40b4512237c77bd04dc76c06a3f8560",
        "address": "185.214.135.205:26656"
      },
      {
        "id": "1539976f4ee196f172369e6f348d60a6e3ec9e93",
        "address": "159.69.147.189:26656"
      },
      {
        "id": "85316823bee88f7b05d0cfc671bee861c0237154",
        "address": "95.217.198.243:26656"
      },
      {
        "id": "eb55b70c9fd8fc0d5530d0662336377668aab3f9",
        "address": "185.194.219.128:26656"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc-1-dig.notional.ventures"
      }
    ],
    "rest": [
      {
        "address": "https://api-1-dig.notional.ventures"
      }
    ]
  },
  "explorers": [
    {
      "kind": "ping.pub",
      "url": "https://ping.pub/dig",
      "tx_page": "https://ping.pub/dig/tx/${txHash}"
    }
  ]
}

=== pyramation/cosmology/packages/cosmos-registry/chain-registry/agoric/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "agoric",
  "status": "live",
  "network_type": "mainnet",
  "pretty_name": "Agoric",
  "chain_id": "agoric-3",
  "bech32_prefix": "agoric",
  "daemon_name": "ag0",
  "node_home": "$HOME/.agoric",
  "genesis": {
    "genesis_url": "https://main.agoric.net/genesis.json"
  },
  "slip44": 564,
  "explorers": [
    {
      "name": "agoric-big-dipper",
      "url": "https://main.explorer.agoric.net/"
    }
  ],
  "codebase": {
    "git_repo": "https://github.com/Agoric/ag0/",
    "recommended_version": "agoric-3.1",
    "compatible_versions": [
      "agoric-3.1"
    ]
  },
  "peers": {
    "seeds": [],
    "persistent_peers": [
      {
        "id": "a26158a5cbb1df581dd6843ac427191af76d6d5d",
        "address": "104.154.240.50:26656"
      },
      {
        "id": "6e26a1b4afa6889f841d7957e8c2b5d50d32d485",
        "address": "95.216.53.26:26656"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://main.rpc.agoric.net:443"
      }
    ],
    "rest": [
      {
        "address": "https://main.api.agoric.net:443"
      }
    ],
    "grpc": [
      {
        "address": "https://main.grpc.agoric.net:443"
      }
    ]
  }
}

=== pyramation/cosmology/packages/registry/chain-registry/irisnet/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "irisnet",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Irisnet",
    "chain_id": "irishub-1",
    "bech32_prefix": "iris",
    "daemon_name": "irisd",
    "node_home": "$HOME/.irisd",
    "key_algos": [
        "secp256k1"
      ],
    "slip44": 118,
    "genesis": {
        "genesis_url": "https://raw.githubusercontent.com/irisnet/mainnet/master/config/genesis.json"
    },
    "codebase": {
        "git_repo": "https://github.com/irisnet/irishub",
        "recommended_version": "v1.2.1",
        "compatible_versions": ["v1.2.1"]
    },
    "peers": {
        "seeds": [
            {
              "id": "6a6de770deaa4b8c061dffd82e9c7f4d40c2165d",
              "address": "seed-1.mainnet.irisnet.org:26656"
            },
            {
              "id": "a17d7923293203c64ba75723db4d5f28e642f469",
              "address": "seed-2.mainnet.irisnet.org:26656"
            }
        ],
        "persistent_peers": [
            {
                "id": "fdc0406afdd3acc63f74f5439e09104f663a7c1f",
                "address": "44.241.177.178:26656",
                "provider": "cosmostation"
            },
            {
                "id": "090bcbe5302e6104821a96c4899912870db04cb9",
                "address": "52.11.128.123:26656",
                "provider": "cosmostation"
            },
            {
                "id": "83b3f989f3ce089afdf733f8aa06e792d7e00c08",
                "address": "3.34.6.30:26656",
                "provider": "cosmostation"
            },
            {
                "id": "87f18756b93d835c59fe5ce2a8da51858837eb5b",
                "address": "54.180.15.28:26656",
                "provider": "Node-A-Team"
            },
            {
                "id": "90e48220190b16cad95145b6213d512d703e5617",
                "address": "138.197.158.189:26656",
                "provider": "Figment"
            },
            {
                "id": "ebfb43ca1b592b5f8a1faf3e2aa1a34e8e1099cc",
                "address": "iris01.dokia.cloud:26656",
                "provider": "Dokia"
            },
            {
                "id": "92fadc989ed29aee0d46afce3226f8565d1f36cb",
                "address": "144.91.116.17:46656",
                "provider": "syncnode"
            },
            {
                "id": "4ac6200974d3fd80a8e49d145a2c254ed37a9b9a",
                "address": "159.69.106.156:26656",
                "provider": "P2P.ORG"
            },
            {
                "id": "4e02a4b4f4350ea2b770cd03dc41fedcadb13176",
                "address": "159.69.55.206:26656",
                "provider": "P2P.ORG"
            },
            {
                "id": "84cc32adca3986b35953886ad075431d318a98b5",
                "address": "52.214.130.28:46656",
                "provider": "stake.fish"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://rpc-iris.keplr.app",
                "provider": "chainapsis"
            }
        ],
        "rest": [
            {
                "address": "https://lcd-iris.keplr.app",
                "provider": "chainapsis"
            }
        ]
    },
    "explorers": [
        {
            "kind": "mintscan",
            "url": "https://www.mintscan.io/iris",
            "tx_page": "https://www.mintscan.io/iris/txs/${txHash}"
        }
    ]
}

=== pyramation/cosmology/packages/registry/chain-registry/bitcanna/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "bitcanna",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "BitCanna",
    "chain_id": "bitcanna-1",
    "bech32_prefix": "bcna",
    "daemon_name": "bcnad",
    "node_home": "$HOME/.bcna",
    "genesis": {
        "genesis_url": "https://raw.githubusercontent.com/BitCannaGlobal/bcna/main/genesis.json"
    },
    "key_algos": [
        "secp256k1"
    ],
    "slip44": 118,
    "fees": {
        "fee_tokens": [
            {
                "denom": "ubcna",
                "fixed_min_gas_price": 0.001
            }
        ]
    },
    "codebase": {
        "git_repo": "https://github.com/BitCannaGlobal/bcna",
        "recommended_version": "v1.3.1",
        "compatible_versions": [
            "v1.3.1"
        ],
        "binaries": {
            "linux/amd64": "https://github.com/BitCannaGlobal/bcna/releases/download/v.1.3.1/bcnad"
        }
    },
    "peers": {
        "seeds": [
            {
                "id": "d6aa4c9f3ccecb0cc52109a95962b4618d69dd3f",
                "address": "seed1.bitcanna.io:26656",
                "provider": "bitcanna"
            },
            {
                "id": "23671067d0fd40aec523290585c7d8e91034a771",
                "address": "seed2.bitcanna.io:26656",
                "provider": "bitcanna"
            }
        ],
        "persistent_peers": [
          {
            "id": "bee230fb347722d7f87d22414f57bf9cbe37a410",
            "address": "95.217.226.95:26039",
            "provider": "EZStaking.io"
          },
          {
            "id": "90ee680b1738344354c48c23ba1e1fd68e071d80",
            "address": "65.108.128.241:26696",
            "provider": "EZStaking.io"
          },
          {
            "id": "7b2d10d188926ea25eb209f037fe4e67e16e06b6",
            "address": "92.222.25.18:26656",
            "provider": "StakeLab"
          },
          {
            "id": "5eb75c20a77ccf960df396b187b86d6324b40123",
            "address": "51.68.226.61:26656",
            "provider": "StakeLab"
          },
          {
            "id": "6bd989f063b89be680fb3c55c4cf1720a892b12c",
            "address": "161.97.96.253:26656",
            "provider": "StakeLab"
          },
          {
            "id": "3cdfe02efd4432280707d2949e064a9d8db412b3",
            "address": "178.62.98.158:26656",
            "provider": "Stakely"
          },
          {
            "id": "d806bb39349751c142627a547c23c586a787ef26",
            "address": "138.68.78.210:26656",
            "provider": "Stakely"
          },
          {
            "id": "ddb620e7c7a6b5a8a53352037cde927681012ab4",
            "address": "65.21.229.209:37656",
            "provider": "Blockscope"
          },
          {
            "id": "df99de6cec9152c517990317b340b8b9a307493c",
            "address": "193.34.144.156:26656",
            "provider": "ParanormalBrothers"
          }
        ]
    },
    "apis": {
        "rpc": [
              {
                "address": "https://rpc.bitcanna.io/",
                "provider": "bitcanna"
              },
              {
                "address": "http://bcna.paranorm.pro:26657/",
                "provider": "ParanormalBrothers"
              },
              {
                "address": "https://rpc.bitcanna.ezstaking.io/",
                "provider": "ezstaking.io"
              },
              {
                "address": "https://rpc-bitcanna.itastakers.com/",
                "provider": "itastaker"
             }
        ],
        "grpc": [
            {
                "address": "https://grpc.bitcanna.io",
                "provider": "bitcanna"
            }
        ],      
        "rest": [
            {
                "address": "https://lcd.bitcanna.io",
                "provider": "bitcanna"
            },
            {
                "address": "https://lcd.bitcanna.ezstaking.io/",
                "provider": "ezstaking.io"
            },
            {
                "address": "https://lcd-bitcanna.itastakers.com/",
                "provider": "itastaker"
            }
        ]
    },
    "explorers": [ 
            {
                "kind": "forbole",
                "url": "https://cosmos-explorer.bitcanna.io",
                "tx_page": "https://cosmos-explorer.bitcanna.io/transactions/${txHash}"
            },
            {
                "kind": "ping-pub",
                "url": "https://ping.pub/bitcanna",
                "tx_page": "https://ping.pub/bitcanna/tx/${txHash}"
            },        
            {
                "kind": "mintscan",
                "url": "https://www.mintscan.io/bitcanna/",
                "tx_page": "https://www.mintscan.io/bitcanna/txs/${txHash}"
            }
    ]
}

=== pyramation/cosmology/packages/cosmos-registry/chain-registry/sifchain/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "sifchain",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Sifchain",
    "chain_id": "sifchain-1",
    "bech32_prefix": "sif",
    "daemon_name": "sifnoded",
    "node_home": "$HOME/.sifnoded",
    "genesis": {
        "genesis_url": "https://github.com/Sifchain/networks/blob/master/betanet/sifchain-1/genesis.json.gz?raw=true"
    },
    "codebase": {
        "git_repo": "https://github.com/Sifchain/sifnode.git",
        "recommended_version": "betanet-0.9.12",
        "compatible_versions": [
            "betanet-0.9.12"
        ],
        "binaries": {
            "linux/amd64": "https://github.com/Sifchain/sifnode/releases/download/betanet-0.9.12/sifnoded-betanet-0.9.12-linux-amd64.zip"
        }
    },
    "peers": {
        "persistent_peers": [
            {
                "id": "0d4981bdaf4d5d73bad00af3b1fa9d699e4d3bc0",
                "address": "44.235.108.41:26656"
            },
            {
                "id": "bcc2d07a14a8a0b3aa202e9ac106dec0bef91fda",
                "address": "13.55.247.60:26656"
            },
            {
                "id": "663dec65b754aceef5fcccb864048305208e7eb2",
                "address": "34.248.110.88:26656"
            },
            {
                "id": "0120f0a48e7e81cc98829ef4f5b39480f11ecd5a",
                "address": "52.76.185.17:26656"
            },
            {
                "id": "6535497f0152293d773108774a705b86c2249a9c",
                "address": "44.238.121.65:26656"
            },
            {
                "id": "fdf5cffc2b20a20fab954d3b6785e9c382762d14",
                "address": "34.255.133.248:26656"
            },
            {
                "id": "8c240f71f9e060277ce18dc09d82d3bbb05d1972",
                "address": "13.211.43.177:26656"
            },
            {
                "id": "9fbcb6bd5a7f20a716564157c4f6296d2faf5f64",
                "address": "18.138.208.95:26656"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://rpc.sifchain.finance:80"
            },
            {
                "address": "https://rpc-archive.sifchain.finance:80"
            }
        ],
        "grpc": [
            {
                "address": "https://grpc.sifchain.finance:80"
            }
        ],
        "rest": [
            {
                "address": "https://api.sifchain.finance:80"
            }
        ]
    }
}
