=== pyramation/cosmology/packages/cosmos-registry/chain-registry/chain.schema.json
{
    "$id": "https://sikka.tech/chain.schema.json",
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "Cosmos Chain",
    "description": "Cosmos Chain.json is a metadata file that contains information about a cosmos sdk based chain.",
    "type": "object",
    "required": [
        "chain_name",
        "chain_id",
        "bech32_prefix"
    ],
    "properties": {
        "chain_name": {
            "type": "string"
        },
        "chain_id": {
            "type": "string"
        },
        "pretty_name": {
            "type": "string"
        },
        "status": {
            "enum": [
                "live",
                "upcoming",
                "killed"
            ]
        },
        "network_type": {
            "enum": [
                "mainnet",
                "testnet"
            ]
        },
        "bech32_prefix": {
            "type": "string"
        },
        "genesis": {
            "type": "object",
            "properties": {
                "genesis_url": {
                    "type": "string"
                }
            }
        },
        "daemon_name": {
            "type": "string"
        },
        "node_home": {
            "type": "string"
        },
        "key_algos": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "secp256k1",
                    "ethsecp256k1",
                    "ed25519",
                    "sr25519"
                ],
                "uniqueItems": true
            }
        },
        "slip44": {
            "type": "number"
        },
        "fees": {
            "type": "object",
            "properties": {
                "fee_tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/fee_token"
                    }
                }
            }
        },
        "codebase": {
            "type": "object",
            "required": [
                "git_repo",
                "recommended_version",
                "compatible_versions"
            ],
            "properties": {
                "git_repo": {
                    "type": "string",
                    "format": "uri"
                },
                "recommended_version": {
                    "type": "string"
                },
                "compatible_versions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "binaries": {
                    "type": "object",
                    "properties": {
                        "linux/amd": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                }
            }
        },
        "peers": {
            "type": "object",
            "properties": {
                "seeds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                },
                "persistent_peers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                }
            }
        },
        "apis": {
            "type": "object",
            "properties": {
                "rpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "rest": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "grpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                }
            }
        },
        "explorers": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/explorer"
            }
        }
    },
    "$defs": {
        "peer": {
            "type": "object",
            "required": [
                "id",
                "address"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "endpoint": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "explorer": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "tx_page": {
                    "type": "string"
                }
            }
        },
        "fee_token": {
            "type": "object",
            "required": [
                "denom"
            ],
            "properties": {
                "denom": {
                    "type": "string"
                },
                "fixed_min_gas_price": {
                    "type": "number"
                }
            }
        }
    }
}

=== pyramation/cosmology/packages/registry/chain-registry/gravitybridge/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "gravitybridge",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Gravity Bridge",
    "chain_id": "gravity-bridge-3",
    "bech32_prefix": "gravity",
    "daemon_name": "gravity",
    "node_home": "$HOME/.gravity",
    "genesis": {
        "genesis_url": "https://raw.githubusercontent.com/Gravity-Bridge/Gravity-Docs/main/genesis.json"
    },
    "key_algos": [
        "secp256k1"
    ],
    "slip44": 118,
    "fees": {
        "fee_tokens": [
            {
                "denom": "ugraviton",
                "fixed_min_gas_price": 0
            }
        ]
    },
    "codebase": {
        "git_repo": "https://github.com/Gravity-Bridge/Gravity-Bridge",
        "recommended_version": "v1.3.3",
        "compatible_versions": [
            "v1.3.0",
            "v1.3.1",
            "v1.3.2",
            "v1.3.3"
        ],
        "binaries": {
            "linux/amd64": "https://github.com/Gravity-Bridge/Gravity-Bridge/releases/download/v1.3.3/gravity-linux-amd64",
            "linux/arm64": "https://github.com/Gravity-Bridge/Gravity-Bridge/releases/download/v1.3.3/gravity-linux-arm64",
            "darwin/amd64": "https://github.com/Gravity-Bridge/Gravity-Bridge/releases/download/v1.3.3/gravity-darwin-amd64",
            "windows/amd64": "https://github.com/Gravity-Bridge/Gravity-Bridge/releases/download/v1.3.3/gravity-windows-amd64.exe"
        }
    },
    "peers": {
        "seeds": [
            {
                "id": "2b089bfb4c7366efb402b48376a7209632380c9c",
                "address": "65.19.136.133:26656",
                "provider": "althea"
            },
            {
                "id": "63e662f5e048d4902c7c7126291cf1fc17687e3c",
                "address": "95.211.103.175:26656",
                "provider": "amhost"
            }
        ],
        "persistent_peers": [
            {
                "id": "21be3f7686c24f8bd9442b325a50f5b5227777a7",
                "address": "202.61.231.15:26656",
                "provider": "SkyNet"
            },
            {
                "id": "9aa7e0c250466a2a147f8b7d2b886b0d45d44ca0",
                "address": "45.138.49.222:26656",
                "provider": "ps350"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://gravitychain.io:26657",
                "provider": "althea"
            },
            {
                "address": "http://gravity-rpc.qwoyn.com:26657",
                "provider": "qwoyn"
            },
            {
                "address": "gravity-bridge-1-08.nodes.amhost.net:26657",
                "provider": "amhost"
            },
            {
                "address": "45.138.49.222:26657",
                "provider": "ps350"
            }
        ],
        "rest": [
            {
                "address": "https://gravitychain.io:1317",
                "provider": "althea"
            },
            {
                "address": "http://gravity-rpc.qwoyn.com:1317",
                "provider": "qwoyn"
            }
        ],
        "grpc": [
            {
                "address": "https://gravitychain.io:9090",
                "provider": "althea"
            },
            {
                "address": "gravity-bridge-1-08.nodes.amhost.net:9090",
                "provider": "amhost"
            }
        ]
    },
    "explorers": [
        {
            "kind": "mintscan",
            "url": "https://www.mintscan.io/gravity-bridge",
            "tx_page": "https://www.mintscan.io/gravity-bridge/${txHash}"
        }
    ]
}

=== pyramation/cosmology/packages/cosmos-registry/chain-registry/cosmoshub/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "cosmoshub",
    "chain_id": "cosmoshub-4",
    "pretty_name": "Cosmos Hub",
    "status": "live",
    "network_type": "mainnet",
    "bech32_prefix": "cosmos",
    "genesis": {
        "genesis_url": "https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz"
    },
    "daemon_name": "gaiad",
    "node_home": "$HOME/.gaia",
    "key_algos": [
        "secp256k1"
    ],
    "slip44": 118,
    "fees": {
        "fee_tokens": [
            {
                "denom": "uatom",
                "fixed_min_gas_price": 0
            }
        ]
    },
    "codebase": {
        "git_repo": "https://github.com/cosmos/gaia",
        "recommended_version": "v6.0.0",
        "compatible_versions": [
            "v6.0.0"
        ],
        "binaries": {
            "linux/amd64": "https://github.com/cosmos/gaia/releases/download/v6.0.0/gaiad-v6.0.0-linux-amd64",
            "linux/arm64": "https://github.com/cosmos/gaia/releases/download/v6.0.0/gaiad-v6.0.0-linux-arm64",
            "darwin/amd64": "https://github.com/cosmos/gaia/releases/download/v6.0.0/gaiad-v6.0.0-darwin-amd64",
            "windows/amd64": "https://github.com/cosmos/gaia/releases/download/v6.0.0/gaiad-v6.0.0-windows-amd64.exe"
        }
    },
    "peers": {
        "seeds": [
            {
                "id": "bf8328b66dceb4987e5cd94430af66045e59899f",
                "address": "public-seed.cosmos.vitwit.com:26656",
                "provider": "vitwit"
            },
            {
                "id": "cfd785a4224c7940e9a10f6c1ab24c343e923bec",
                "address": "164.68.107.188:26656"
            },
            {
                "id": "d72b3011ed46d783e369fdf8ae2055b99a1e5074",
                "address": "173.249.50.25:26656"
            },
            {
                "id": "ba3bacc714817218562f743178228f23678b2873",
                "address": "public-seed-node.cosmoshub.certus.one:26656",
                "provider": "certusone"
            },
            {
                "id": "3c7cad4154967a294b3ba1cc752e40e8779640ad",
                "address": "84.201.128.115:26656"
            },
            {
                "id": "366ac852255c3ac8de17e11ae9ec814b8c68bddb",
                "address": "51.15.94.196:26656"
            }
        ],
        "persistent_peers": [
            {
                "id": "ee27245d88c632a556cf72cc7f3587380c09b469",
                "address": "45.79.249.253:26656"
            },
            {
                "id": "538ebe0086f0f5e9ca922dae0462cc87e22f0a50",
                "address": "34.122.34.67:26656"
            },
            {
                "id": "d3209b9f88eec64f10555a11ecbf797bb0fa29f4",
                "address": "34.125.169.233:26656"
            },
            {
                "id": "bdc2c3d410ca7731411b7e46a252012323fbbf37",
                "address": "34.83.209.166:26656"
            },
            {
                "id": "585794737e6b318957088e645e17c0669f3b11fc",
                "address": "54.160.123.34:26656"
            },
            {
                "id": "11dfe200894f38e411beca77928e9dd118e66813",
                "address": "94.130.98.157:26656"
            },
            {
                "id": "5b4ed476e01c49b23851258d867cc0cfc0c10e58",
                "address": "206.189.4.227:26656"
            },
            {
                "id": "654f47a762c8f9257aef4a44c1fb5014916d8b20",
                "address": "99.79.60.15:26656"
            },
            {
                "id": "366ac852255c3ac8de17e11ae9ec814b8c68bddb",
                "address": "51.15.94.196:26656"
            },
            {
                "id": "d6318b3bd51a5e2b8ed08f2e520d50289ed32bf1",
                "address": "52.79.43.100:26656"
            },
            {
                "id": "1bfda3d59e70290a3dada9bb809dd954371850d3",
                "address": "54.180.225.240:26656"
            },
            {
                "id": "6ee94c2093505e8790442c054e6e1e0211d36583",
                "address": "44.239.140.195:26656"
            },
            {
                "id": "ec779a2741da6dd2ccdaa6dfc0bebb10e595dfa4",
                "address": "50.18.113.67:26656"
            },
            {
                "id": "cfd785a4224c7940e9a10f6c1ab24c343e923bec",
                "address": "164.68.107.188:26656"
            },
            {
                "id": "d72b3011ed46d783e369fdf8ae2055b99a1e5074",
                "address": "173.249.50.25:26656"
            },
            {
                "id": "047f723806ee702b211e7227f89eacd829aabd86",
                "address": "52.9.212.125:26656"
            },
            {
                "id": "b0e746acb6fbed7a0311fe21cfb2ee94581ca3bc",
                "address": "51.79.21.187:26656"
            },
            {
                "id": "82772547c4575c18dfe6e75aafe521cf7d4dc8de",
                "address": "142.93.157.186:26656"
            },
            {
                "id": "3c7cad4154967a294b3ba1cc752e40e8779640ad",
                "address": "84.201.128.115:26656"
            },
            {
                "id": "f122129f53b7c584df6cee77716dcc636d5c5e18",
                "address": "167.172.59.196:26656"
            },
            {
                "id": "241b17dba97a2ed3c3747d12781fb86c9706e2d4",
                "address": "95.179.136.131:26656"
            },
            {
                "id": "f1b16c603f3a0e59f0ce5179dc80f549a7ecd0e2",
                "address": "sentries.us-east1.iqext.net:26656"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://cosmoshub.validator.network/",
                "provider": "validatornetwork"
            },
            {
                "address": "https://cosmoshub-4.technofractal.com:443",
                "provider": "strangelove-ventures"
            },
            {
                "address": "https://rpc.cosmos.network:443",
                "provider": "tendermint-inc"
            },
            {
                "address": "https://rpc-cosmoshub.blockapsis.com",
                "provider": "chainapsis"
            }
        ],
        "rest": [
            {
                "address": "https://lcd-cosmoshub.blockapsis.com",
                "provider": "chainapsis"
            }  
        ]
    },
    "explorers": [
        {
            "kind": "mintscan",
            "url": "https://www.mintscan.io/cosmos",
            "tx_page": "https://www.mintscan.io/cosmos/txs/${txHash}"
        }
    ]
}

=== pyramation/cosmology/packages/registry/chain-registry/provenance/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "provenance",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Provenance Blockchain",
    "chain_id": "pio-mainnet-1",
    "bech32_prefix": "pb",
    "daemon_name": "provenanced",
    "node_home": "$HOME/Provenance",
    "genesis": {
        "genesis_url": "https://raw.githubusercontent.com/provenance-io/mainnet/main/pio-mainnet-1/genesis.json"
    },
    "key_algos": [
        "secp256k1"
    ],
    "slip44": 505,
    "fees": {
        "fee_tokens": [
            {
                "denom": "nhash",
                "fixed_min_gas_price": 1905
            }
        ]
    },
    "codebase": {
        "git_repo": "https://github.com/provenance-io/provenance",
        "recommended_version": "v1.7.6",
        "compatible_versions": [
            "v1.7.5",
            "v1.7.6"
        ],
        "binaries": {
            "linux/amd64": "https://github.com/provenance-io/provenance/releases/download/v1.7.6/provenance-linux-amd64-v1.7.6.zip",
            "darwin/amd64": "https://github.com/provenance-io/provenance/releases/download/v1.7.6/provenance-darwin-amd64-v1.7.6.zip"
        }
    },
    "peers": {
        "seeds": [

        {
            "id": "4bd2fb0ae5a123f1db325960836004f980ee09b4",
            "address": "seed-0.provenance.io:26656",
            "provider": "figure"
        },
        {
            "id": "048b991204d7aac7209229cbe457f622eed96e5d",
            "address": "seed-1.provenance.io:26656",
            "provider": "figure"
        }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://rpc.provenance.io/",
                "provider": "figure"
            }
        ],
        "rest": [
            {
                "address": "https://api.provenance.io",
                "provider": "figure"
            }
        ]
    },
    "explorers": [
        {
            "kind": "provenance",
            "url": "https://explorer.provenance.io",
            "tx_page": "https://explorer.provenance.io/tx/${txHash}"
        },
        {
            "kind": "bigdipper",
            "url": "https://bigdipper.provenance.io",
            "tx_page": "https://bigdipper.provenance.io/transactions/${txHash}"
        },
        {
            "kind": "hubble",
            "url": "https://hubble.figment.io/provenance/chains/pio-mainnet-1",
            "tx_page": "https://hubble.figment.io/provenance/chains/pio-mainnet-1/${block}/transactions/${txHash}"
        }, 
        {
            "kind": "ping-pub",
            "url": "https://ping.pub/provenance",
            "tx_page": "https://ping.pub/provenance/tx/${txHash}"
        }           
    ]
}

=== pyramation/cosmology/packages/registry/chain-registry/panacea/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "panacea",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Panacea",
    "chain_id": "panacea-3",
    "bech32_prefix": "panacea",
    "daemon_name": "panacead",
    "node_home": "$HOME/.panacead",
    "genesis": {
        "genesis_url": "https://github.com/medibloc/panacea-mainnet/raw/master/panacea-3/genesis.json"
    },
    "key_algos": [
        "secp256k1"
    ],
    "slip44": 371,
    "fees": {
        "fee_tokens": [
            {
                "denom": "umed",
                "fixed_min_gas_price": 5
            }
        ]
    },
    "codebase": {
        "git_repo": "https://github.com/medibloc/panacea-core",
        "recommended_version": "v2.0.2",
        "compatible_versions": [
            "v2.0.2"
        ],
        "binaries": {}
    },
    "peers": {
        "persistent_peers": [
            {
                "id": "e93f5df69cc1b9bda230b3efcf162d4672293ded",
                "address": "3.35.82.40:26656",
                "provider": "medibloc"
            },
            {
                "id": "0e0db1c7ab1e37c76f2ceced0bb72e1c60ef17a6",
                "address": "13.124.96.254:26656",
                "provider": "medibloc"
            },
            {
                "id": "a83232db3a40e486b54b1463a43431e8490b808b",
                "address": "52.79.108.35:26656",
                "provider": "medibloc"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://rpc.gopanacea.org",
                "provider": "medibloc"
            }
        ],
        "rest": [
            {
                "address": "https://api.gopanacea.org",
                "provider": "medibloc"
            }
        ]
    },
    "explorers": [
        {
            "kind": "mintscan",
            "url": "https://www.mintscan.io/medibloc",
            "tx_page": "https://www.mintscan.io/medibloc/txs/${txHash}"
        },
        {
            "kind": "bigdipper",
            "url": "https://explorer.gopanacea.org",
            "tx_page": "https://explorer.gopanacea.org/transactions/${txHash}"
        }
    ]
}

=== pyramation/cosmology/packages/cosmos-registry/chain-registry/terra/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "terra",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Terra",
    "chain_id": "columbus-5",
    "daemon_name": "terrad",
    "node_home": "$HOME/.terra",
    "bech32_prefix": "terra",
    "genesis": {
        "genesis_url": "https://columbus-genesis.s3.ap-northeast-1.amazonaws.com/columbus-5-genesis.json"
    },
    "codebase": {
        "git_repo": "https://github.com/terra-money/core/",
        "recommended_version": "v0.5.17",
        "compatible_versions": [
            "v0.5.17",
            "v0.5.16"
        ],
        "binaries": {
            "linux/amd64": "https://github.com/terra-money/core/releases/download/v0.5.17/terra_0.5.17_Linux_x86_64.tar.gz",
            "darwin/amd64": "https://github.com/terra-money/core/releases/download/v0.5.17/terra_0.5.17_Darwin_x86_64.tar.gz"
        }
    },
    "peers": {
        "seeds": [
            {
                "id": "e999fc20aa5b87c1acef8677cf495ad85061cfb9",
                "address": "seed.terra.delightlabs.io:26656"
            },
            {
                "id": "6d8e943c049a80c161a889cb5fcf3d184215023e",
                "address": "public-seed2.terra.dev:26656"
            },
            {
                "id": "87048bf71526fb92d73733ba3ddb79b7a83ca11e",
                "address": "public-seed.terra.dev:26656"
            }
        ],
        "persistent_peers": [
            {
                "id": "3ddf51347ba7c2bc4a8e1e26ee9d1cbf81034516",
                "address": "162.55.244.250:27656"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://terra-rpc.easy2stake.com:443",
                "provider": "Easy2stake"
            },
            {
                "address": "http://64.227.72.101:26657",
                "provider": "cryptocrew"
            },
            {
                "address": "http://public-node.terra.dev:26657",
                "provider": "Terra"
            },
            {
                "address": "https://terra.technofractal.com:443",
                "provider": "strangelove-ventures"
            }
        ],
        "rest": [
            {
                "address": "http://64.227.72.101:1317",
                "provider": "cryptocrew"
            },
            {
                "address": "https://blockdaemon-terra-lcd.api.bdnodes.net:1317",
                "provider": "Blockdaemon"
            }
        ]
    }
}

=== pyramation/cosmology/packages/registry/chain-registry/sentinel/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "sentinel",
  "status": "live",
  "network_type": "mainnet",
  "pretty_name": "Sentinel",
  "chain_id": "sentinelhub-2",
  "bech32_prefix": "sent",
  "slip44": 750,
  "genesis": {
    "genesis_url": "https://raw.githubusercontent.com/sentinel-official/networks/main/sentinelhub-2/genesis.zip"
  },
  "codebase": {
    "git_repo": "https://github.com/sentinel-official/hub",
    "recommended_version": "v0.6.2",
    "compatible_versions": ["v0.6.2"]
  },
  "daemon_name": "sentinelhub",
  "node_home": "$HOME/.sentinelhub",
  "key_algos": ["secp256k1"],
  "peers": {
    "seeds": [
      {
        "id": "c3aa0ff9b3eb17be1b0a26d7c8a5683e8e528e1a",
        "address": "159.89.192.105:26656"
      }
    ],
    "persistent_peers": [
      {
        "id": "05fe2a7847fd27345250915fd06752c424f40651",
        "address": "85.222.234.135:26656"
      },
      {
        "id": "387027e3b1180d3a619cbbf3462704a490785963",
        "address": "54.176.90.228:26656"
      },
      {
        "id": "63bd9cfce0f0d274aad5b166dd06d829021aec43",
        "address": "121.78.247.243:56656"
      },
      {
        "id": "855807cc6a919c22ec943050ebb5c80b23724ed0",
        "address": "3.239.11.246:26656"
      },
      {
        "id": "8caefbf8f4318ecc93f2c901cf11470e4a16c818",
        "address": "161.97.135.122:26656"
      },
      {
        "id": "9174af5f16f74660cccf49f893d243949af45f7f",
        "address": "54.177.29.46:26656"
      },
      {
        "id": "9fa528bd2b9e7c80724a1d8a4e1a2a8a83e7d123",
        "address": "142.93.72.221:26656"
      },
      {
        "id": "a77f6a094578dad899e2f40e0626b4c6d4705311",
        "address": "3.36.165.232:26656"
      },
      {
        "id": "bd45a11390d16d128a9eeea3935b53d7a1a3c120",
        "address": "15.236.127.69:26656"
      },
      {
        "id": "cdb8dd7628460a546ce1594ca0bc0c20366514cf",
        "address": "34.72.64.178:26656"
      },
      {
        "id": "d1efceccb04ded9a604e5235f76da86872157d68",
        "address": "161.97.149.223:26656"
      },
      {
        "id": "e00b23444cc8dbb353d5faa765ab36cfc0116b57",
        "address": "83.60.98.134:28685"
      },
      {
        "id": "e5ee89bd4fc371c6a0e66d2b8daefd891b6b87b5",
        "address": "157.90.117.58:26656"
      },
      {
        "id": "f7ceb735606f90df7eb6cd987641876955b6e325",
        "address": "46.4.55.150:36656"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc-sentinel.keplr.app",
        "provider": "chainapsis"
      }
    ],
    "rest": [
      {
        "address": "https://lcd-sentinel.keplr.app",
        "provider": "chainapsis"
      }
    ]
  }
}

=== pyramation/cosmology/packages/cosmos-registry/chain-registry/bandchain/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "bandchain",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "BandChain",
    "chain_id": "laozi-mainnet",
    "daemon_name": "bandd",
    "node_home": "$HOME/.band",
    "bech32_prefix": "band",
    "slip44": 494,
    "genesis": {
        "genesis_url": "https://raw.githubusercontent.com/bandprotocol/launch/master/laozi-mainnet/genesis.json"
    },
    "codebase": {
        "git_repo": "https://github.com/bandprotocol/chain",
        "recommended_version": "v2.3.2",
        "compatible_versions": [
            "v2.3.2"
        ]
    },
    "peers": {
        "seeds": [
            {
                "id": "8d42bdcb6cced03e0b67fa3957e4e9c8fd89015a",
                "address": "34.87.86.195:26656"
            },
            {
                "id": "543e0cab9c3016a0e99775443a17bcf163038912",
                "address": "34.150.156.78:26656"
            }
        ],
        "persistent_peers": [
            {
                "id": "98823087b61d442a4ab86998709c77b2e517ee78",
                "address": "35.240.152.216:26656"
            },
            {
                "id": "3ea84babead3d6bc488810a0f2cf0744cf5c68fe",
                "address": "34.86.22.251:26656"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "http://rpc.laozi1.bandchain.org:80",
                "provider": "bandprotocol"
            }
        ],
        "rest": [
            {
                "address": "https://laozi1.bandchain.org/api",
                "provider": "bandprotocol"
            }
        ]
    },
    "explorers": [
        {
            "kind": "cosmoscan",
            "url": "https://cosmoscan.io",
            "tx_page": "https://cosmoscan.io/tx/{txHash}"
        }
    ]
}
