=== pyramation/cosmology/packages/cosmos-registry/chain-registry/chain.schema.json
{
    "$id": "https://sikka.tech/chain.schema.json",
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "Cosmos Chain",
    "description": "Cosmos Chain.json is a metadata file that contains information about a cosmos sdk based chain.",
    "type": "object",
    "required": [
        "chain_name",
        "chain_id",
        "bech32_prefix"
    ],
    "properties": {
        "chain_name": {
            "type": "string"
        },
        "chain_id": {
            "type": "string"
        },
        "pretty_name": {
            "type": "string"
        },
        "status": {
            "enum": [
                "live",
                "upcoming",
                "killed"
            ]
        },
        "network_type": {
            "enum": [
                "mainnet",
                "testnet"
            ]
        },
        "bech32_prefix": {
            "type": "string"
        },
        "genesis": {
            "type": "object",
            "properties": {
                "genesis_url": {
                    "type": "string"
                }
            }
        },
        "daemon_name": {
            "type": "string"
        },
        "node_home": {
            "type": "string"
        },
        "key_algos": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "secp256k1",
                    "ethsecp256k1",
                    "ed25519",
                    "sr25519"
                ],
                "uniqueItems": true
            }
        },
        "slip44": {
            "type": "number"
        },
        "fees": {
            "type": "object",
            "properties": {
                "fee_tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/fee_token"
                    }
                }
            }
        },
        "codebase": {
            "type": "object",
            "required": [
                "git_repo",
                "recommended_version",
                "compatible_versions"
            ],
            "properties": {
                "git_repo": {
                    "type": "string",
                    "format": "uri"
                },
                "recommended_version": {
                    "type": "string"
                },
                "compatible_versions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "binaries": {
                    "type": "object",
                    "properties": {
                        "linux/amd": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                }
            }
        },
        "peers": {
            "type": "object",
            "properties": {
                "seeds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                },
                "persistent_peers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                }
            }
        },
        "apis": {
            "type": "object",
            "properties": {
                "rpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "rest": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "grpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                }
            }
        },
        "explorers": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/explorer"
            }
        }
    },
    "$defs": {
        "peer": {
            "type": "object",
            "required": [
                "id",
                "address"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "endpoint": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "explorer": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "tx_page": {
                    "type": "string"
                }
            }
        },
        "fee_token": {
            "type": "object",
            "required": [
                "denom"
            ],
            "properties": {
                "denom": {
                    "type": "string"
                },
                "fixed_min_gas_price": {
                    "type": "number"
                }
            }
        }
    }
}

=== pyramation/cosmology/packages/cosmos-registry/chain-registry/carbon/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "carbon",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Carbon",
    "chain_id": "carbon-1",
    "bech32_prefix": "swth",
    "daemon_name": "carbond",
    "node_home": "$HOME/.carbond",
    "genesis": {
        "genesis_url": "https://github.com/Switcheo/carbon-bootstrap/raw/master/carbon-1/genesis.json"
    },
    "key_algos": [
        "secp256k1"
    ],
    "slip44": 118,
    "fees": {
        "fee_tokens": [
            {
                "denom": "swth",
                "fixed_min_gas_price": 0
            }
        ]
    },
    "codebase": {
        "git_repo": "https://github.com/Switcheo/carbon-bootstrap",
        "recommended_version": "v2.2.0",
        "compatible_versions": [],
        "binaries": {
            "linux/amd64": "https://github.com/Switcheo/carbon-bootstrap/releases/download/v2.2.0/carbond2.2.0-mainnet.linux-amd64.tar.gz",
            "linux/arm64": "https://github.com/Switcheo/carbon-bootstrap/releases/download/v2.2.0/carbond2.2.0-mainnet.linux-ard64.tar.gz"
        }
    },
    "peers": {
        "seeds": [
            {
                "id": "d93ed6a1f43dd0904dc5e2ab8680d4049b057b17",
                "address": "13.215.17.91:26656",
                "provider": "switcheo-labs"
            },
            {
                "id": "70581c625fc1933bc273ca7a8d5e9ded3d1bcc97",
                "address": "13.213.113.113:26656",
                "provider": "switcheo-labs"
            },
            {
                "id": "e3f02a9f3ca22724b3a67bba9183113645c9c7d9",
                "address": "54.179.11.177:26656",
                "provider": "switcheo-labs"
            }
        ],
        "persistent_peers": [
            {
                "id": "b638cc8fc5b3d7867281081efce15e5a989339ac",
                "address": "188.166.191.195:26656",
                "provider": "intsol"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://tm-api.carbon.network",
                "provider": "switcheo-labs"
            }
        ],
        "rest": [
            {
                "address": "https://api.carbon.network",
                "provider": "switcheo-labs"
            }
        ]
    },
    "explorers": [
        {
            "kind": "carbonscan",
            "url": "https://scan.carbon.network",
            "tx_page": "https://scan.carbon.network/transaction/${txHash}?net=main"
        }
    ]
}

=== pyramation/cosmology/packages/registry/chain-registry/injective/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "injective",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Injective",
    "chain_id": "injective-1",
    "bech32_prefix": "inj",
    "slip44": 60,
    "daemon_name": "injectived",
    "node_home": "$HOME/.injectived",
    "genesis": {
        "genesis_url": "https://raw.githubusercontent.com/InjectiveLabs/mainnet-config/master/10001/genesis.json"
    },
    "codebase": {
        "git_repo": "https://github.com/InjectiveLabs/injective-chain-releases",
        "recommended_version": "v1.1.1-1637059884",
        "compatible_versions": [
            "v1.1.1-1637059884"
        ],
        "binaries": {
            "linux/amd64": "https://github.com/InjectiveLabs/injective-chain-releases/releases/download/v1.1.1-1637059884/linux-amd64.zip",
            "darwin/amd64": "https://github.com/InjectiveLabs/injective-chain-releases/releases/download/v1.1.1-1637059884/darwin-amd64.zip"
        }
    },
    "peers": {
        "seeds": [
            {
                "id": "2ee7586d8e5a4a2020dafddf68efdfdaa3606cc3",
                "address": "145.40.67.249:26656",
                "provider": "injectiveprotocol"
            },
            {
                "id": "7bb20f8e9fa73e34d0d21862528d5fba839eeb56",
                "address": "145.40.73.39:26656",
                "provider": "injectiveprotocol"
            },
            {
                "id": "de25916e19083d44d67e0c336199b215523f1578",
                "address": "145.40.68.223:26656",
                "provider": "injectiveprotocol"
            },
            {
                "id": "1a2ccd9c436eae54d6c767ad566c58dce78f8be2",
                "address": "145.40.68.125:26656",
                "provider": "injectiveprotocol"

            }
        ],
    "persistent_peers": [
        {
            "id": "2ee7586d8e5a4a2020dafddf68efdfdaa3606cc3",
            "address": "2ee7586d8e5a4a2020dafddf68efdfdaa3606cc3@145.40.67.249:26656",
            "provider": "injectiveprotocol"

        },
        {
            "id": "30e81e1b785eaf82d2260e932251c02c95787740",
            "address": "30e81e1b785eaf82d2260e932251c02c95787740@86.109.11.215:26656",
            "provider": "injectiveprotocol"
        }
    ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://injective-rpc.api.chainlayer.network/",
                "provider": "chainlayer"
            }
        ],
         "rest": [
            {
                "address": "https://public.lcd.injective.network",
                "provider": "injectiveprotocol"
            },
            {
                "address": "https://injective-lcd.api.chainlayer.network/",
                "provider": "chainlayer"
            }
        ],
        "grpc": []
    },
    "explorers": [
        {
         "kind": "injectiveprotocol",
         "url": "https://explorer.injective.network/",
         "tx_page": "https://explorer.injective.network/transaction/${txHash}"
        },
        {
            "kind": "ping-pub",
            "url": "https://ping.pub/injective",
            "tx_page": "https://ping.pub/injective/tx/${txHash}"
        }
    ]
}

=== pyramation/cosmology/packages/cosmos-registry/chain-registry/emoney/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "emoney",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "e-Money",
    "chain_id": "emoney-3",
    "bech32_prefix": "emoney",
    "daemon_name": "emd",
    "node_home": "$HOME/.emd",
    "genesis": {
        "genesis_url": "https://raw.githubusercontent.com/e-money/networks/master/emoney-3/genesis.json"
    },
    "key_algos": [
        "secp256k1"
    ],
    "slip44": 118,
    "fees": {
        "fee_tokens": [
            {
                "denom": "ungm"
            },
            {
                "denom": "eeur"
            },
            {
                "denom": "echf"
            },
            {
                "denom": "edkk"
            },
            {
                "denom": "enok"
            },
            {
                "denom": "esek"
            }
        ]
    },
    "codebase": {
        "git_repo": "https://github.com/e-money/em-ledger",
        "recommended_version": "v1.1.3",
        "compatible_versions": [
            "v1.1.3"
        ]
    },
    "peers": {
        "seeds": [
            {
                "id": "708e559271d4d75d7ea2c3842e87d2e71a465684",
                "address": "seed-1.emoney.validator.network:28656",
                "provider": "validator.network"
            },
            {
                "id": "336cdb655ea16413a8337e730683ddc0a24af9de",
                "address": "seed-2.emoney.validator.network:28656",
                "provider": "validator.network"
            },
            {
                "id": "ecec8933d80da5fccda6bdd72befe7e064279fc1",
                "address": "207.180.213.123:26676",
                "provider": "easy2stake"
            },
            {
                "id": "0ad7bc7687112e212bac404670aa24cd6116d097",
                "address": "50.18.83.75:26656",
                "provider": "B-Harvest"
            },
            {
                "id": "1723e34f45f54584f44d193ce9fd9c65271ca0b3",
                "address": "13.124.62.83:26656",
                "provider": "B-Harvest"
            },
            {
                "id": "34eca4a9142bf9c087a987b572c114dad67a8cc5",
                "address": "172.105.148.191:26656",
                "provider": "Cat Boss"
            },
            {
                "id": "0b186517e4d82eb4c000a567e486b7b96bf19752",
                "address": "44.195.95.22:26656",
                "provider": "Cat Boss"
            },
            {
                "id": "0b186517e4d82eb4c000a567e486b7b96bf19752",
                "address": "44.195.95.22:26656",
                "provider": "Mr K"
            },
            {
                "id": "eed66085c975189e3d498fe61af2fcfb3da34924",
                "address": "217.79.184.40:26656",
                "provider": "MissionControl"
            },
            {
                "id": "226d713acb10a1cd09b3b890406b886d7b071cf2",
                "address": "10.105.2.101:26656",
                "provider": "ATEAM"
            },
            {
                "id": "552cb87c40f879c8c41005eeb36030502671e7a4",
                "address": "18.156.91.213:26656",
                "provider": "ATEAM"
            },
            {
                "id": "170255a4a9b120786d2d6c3931ebf0125087cca0",
                "address": "62.171.171.139:26656",
                "provider": "KalpaTech"
            },
            {
                "id": "d12ac664ff9766e0535c836173111e3eed462e79",
                "address": "185.144.83.157:26656",
                "provider": "Inotel"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://rpc-emoney.keplr.app",
                "provider": "chainapsis"
            },
            {
                "address": "https://emoney.validator.network",
                "provider": "e-Money"
            }
        ],
        "rest": [
            {
                "address": "https://lcd-emoney.keplr.app",
                "provider": "chainapsis"
            },
            {
                "address": "https://emoney.validator.network/api/",
                "provider": "e-Money"
            }
        ]
    },
    "explorers": [
        {
            "kind": "bigdipper",
            "url": "https://emoney.bigdipper.live/",
            "tx_page": "https://emoney.bigdipper.live/transactions/${txHash}"
        },
        {
            "kind": "mintscan",
            "url": "https://www.mintscan.io/emoney",
            "tx_page": "https://www.mintscan.io/emoney/txs/${txHash}"
        }
    ]
}

=== pyramation/cosmology/packages/registry/chain-registry/likecoin/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "likecoin",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "LikeCoin",
    "chain_id": "likecoin-mainnet-2",
    "bech32_prefix": "cosmos",
    "daemon_name": "liked",
    "node_home": "$HOME/.liked",
    "genesis": {
        "genesis_url": "https://raw.githubusercontent.com/likecoin/mainnet/982c14399089950a59d3ebbedcbbc7ead6040457/genesis.json"
    },
    "key_algos": [
        "secp256k1"
    ],
    "slip44": 118,
    "fees": {
        "fee_tokens": [
            {
                "denom": "nanolike"
            }
        ]
    },
    "codebase": {
        "git_repo": "https://github.com/likecoin/likecoin-chain",
        "recommended_version": "fotan-1",
        "compatible_versions": [
            "fotan-1"
        ]
    },
    "peers": {
        "seeds": [
            {
                "id": "913bd0f4bea4ef512ffba39ab90eae84c1420862",
                "address": "34.82.131.35:26656",
                "provider": "likecoin"
            },
            {
                "id": "e44a2165ac573f84151671b092aa4936ac305e2a",
                "address": "nnkken.dev:26656",
                "provider": "nnkken"
            }
        ],
        "persistent_peers": [
            {
                "id": "75822abfbcc23dcefd025e245b46e2dec5357f75",
                "address": "207.246.101.4:26656",
                "provider": "forbole"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://mainnet-node.like.co/rpc/",
                "provider": "likecoin"
            }
        ],
        "rest": [
            {
                "address": "https://mainnet-node.like.co",
                "provider": "likecoin"
            }
        ]
    },
    "explorers": [
        {
            "kind": "bigdipper",
            "url": "https://likecoin.bigdipper.live/",
            "tx_page": "https://likecoin.bigdipper.live/transactions/${txHash}"
        },
        {
            "kind": "lunie-ng",
            "url": "https://stake.like.co/"
        },
        {
            "kind": "ping-pub",
            "url": "https://ping.pub/likecoin",
            "tx_page": "https://ping.pub/likecoin/tx/${txHash}"
        }
    ]
}

=== pyramation/cosmology/packages/registry/chain-registry/vidulum/chain.json
{
  "$schema": "../chain.schema.json",
  "chain_name": "vidulum",
  "status": "live",
  "network_type": "mainnet",
  "pretty_name": "Vidulum",
  "chain_id": "vidulum-1",
  "bech32_prefix": "vdl",
  "daemon_name": "vidulumd",
  "node_home": "$HOME/.vidulum",
  "genesis": {
    "genesis_url": "https://github.com/vidulum/mainnet/blob/main/genesis.json"
  },
  "key_algos": ["secp256k1"],
  "slip44": 370,
  "fees": {
    "fee_tokens": [
      {
        "denom": "uvdl",
        "fixed_min_gas_price": 0
      }
    ]
  },
  "codebase": {
    "git_repo": "https://github.com/vidulum/mainnet",
    "recommended_version": "v1.0.0",
    "compatible_versions": ["v1.0.0"],
    "binaries": {
      "linux/amd64": "https://github.com/vidulum/mainnet/releases/download/v1.0.0/vidulum_linux_amd64.tar.gz",
      "linux/arm64": "https://github.com/vidulum/mainnet/releases/download/v1.0.0/vidulum_linux_arm64.tar.gz",
      "darwin/amd64": "https://github.com/vidulum/mainnet/releases/download/v1.0.0/vidulum_darwin_amd64.tar.gz",
      "windows/amd64": "https://github.com/vidulum/mainnet/releases/download/v1.0.0/vidulum_windows_amd64.zip"
    }
  },
  "peers": {
    "seeds": [
      {
        "id": "883ec7d5af7222c206674c20c997ccc5c242b38b",
        "address": "ec2-3-82-120-39.compute-1.amazonaws.com:26656",
        "provider": "notional"
      }
    ],
    "persistent_peers": [
      {
        "id": "3bf3d98dfd4000dd5ff8189882a9f96848b99b87",
        "address": "137.220.60.196:26656",
        "provider": "vidulum"
      },
      {
        "id": "7a44ea6ecb59b0e4bd01b58a75163ec64b164bb4",
        "address": "63.210.148.24:26656",
        "provider": "vidulum"
      },
      {
        "id": "52051fef449e76eb399966312f523e8e5e27490b",
        "address": "95.217.118.211:26656",
        "provider": "minerpool"
      },
      {
        "id": "cae7d9d21c1752300277eab72d861b0c6638b2e3",
        "address": "164.68.119.151:26656",
        "provider": "bluebird"
      },
      {
        "id": "209688f5bccb88f6397a97cc11ab545a014aa559",
        "address": "137.184.92.115:26656",
        "provider": "1square"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://mainnet-rpc.vidulum.app/",
        "provider": "vidulum"
      }
    ],
    "rest": [
      {
        "address": "https://mainnet-lcd.vidulum.app",
        "provider": "vidulum"
      }
    ]
  },
  "explorers": [
    {
      "kind": "Ping",
      "url": "https://explorers.vidulum.app/vidulum",
      "tx_page": "https://explorers.vidulum.app/vidulum/tx/${txHash}"
    },
    {
      "kind": "Ping",
      "url": "https://ping.pub/vidulum",
      "tx_page": "https://ping.pub/vidulum/tx/${txHash}"
    }
  ]
}

=== pyramation/cosmology/packages/registry/chain-registry/thorchain/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "thorchain",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "THORChain",
    "chain_id": "thor-1",
    "bech32_prefix": "thor",
    "daemon_name": "thord",
    "node_home": "$HOME/.thornode",
    "slip44": 931,
    "genesis": {
        "genesis_url": "https://rpc.thorchain.info/genesis"
    },
    "codebase": {
        "git_repo": "https://gitlab.com/thorchain/thornode",
        "recommended_version": "chaosnet-multichain",
        "compatible_versions": [
            "chaosnet-multichain"
        ]
    },
    "peers": {
        "seeds": [
            {
                "id": "eef0b258a711fc2be06da8eb25a53ebd8e16da62",
                "address": "13.36.197.238:27146"
            },
            {
                "id": "02041c659d8588f225b3352df8636e05dcd239f7",
                "address": "18.169.114.61:27146"
            },
            {
                "id": "88783fa86645c41aaaf031f31df2ee1d74413880",
                "address": "18.202.205.93:27146"
            },
            {
                "id": "00783ce232787999a7b3ccdfdbd493f371203e60",
                "address": "51.136.76.139:27146"
            },
            {
                "id": "c3f3f920a7003585ea6489344b41dd248ffa1e8f",
                "address": "188.166.204.206:27146"
            },
            {
                "id": "46040fd7b9450772c43fa406ef821d5eb3f79114",
                "address": "134.209.136.64:27146"
            },
            {
                "id": "7581fbca995486787ac3619cddf4137e110aff11",
                "address": "143.198.247.31:27146"
            },
            {
                "id": "dcd52d42ee465dd23b5806b30eca8df8e9e76c5d",
                "address": "138.197.48.191:27146"
            },
            {
                "id": "3a520c0e7c2af48d33cfb425af9ea9caa5917b1e",
                "address": "18.214.28.114:27146"
            },
            {
                "id": "48b675fbb3bf968ebee7e366d72bb5580aa8162e",
                "address": "139.59.217.54:27146"
            },
            {
                "id": "f1513684dd9d574715304bf3dd3b53fbcce65909",
                "address": "34.145.173.217:27146"
            },
            {
                "id": "2dde4b30bf913c9b9adecb6b835b2654b50c5698",
                "address": "3.124.212.184:27146"
            },
            {
                "id": "97ab3ae9df723ef763d90128663e7de0f0568dbe",
                "address": "54.217.4.198:27146"
            },
            {
                "id": "7c3b0a1fd70c5c0154e40f6e1276f8dd171117e5",
                "address": "136.244.65.26:27146"
            },
            {
                "id": "79b84e53bd5e4c1a3ef309346136cc7528ba0bdf",
                "address": "64.225.81.243:27146"
            },
            {
                "id": "d8628418e84acf19a330dddbed3173cfb4a020a9",
                "address": "138.197.48.59:27146"
            },
            {
                "id": "7c884bbc48abbadbb0fb85bfaa1dff9e94eac401",
                "address": "143.244.211.46:27146"
            },
            {
                "id": "8757a66381b4182f74809461fd8a3fcaf203a820",
                "address": "34.212.187.195:27146"
            },
            {
                "id": "6a35ed1a50ee76f72d1cd5c688f2e5f7fbc5da25",
                "address": "52.228.231.228:27146"
            },
            {
                "id": "5842bbfc26cf87c2ae3db418a835511ef2a39277",
                "address": "3.96.249.116:27146"
            },
            {
                "id": "83d3c662b1287bc9292d75b4909cff63b119cc78",
                "address": "18.206.141.33:27146"
            },
            {
                "id": "14d576eb4a1a5a2e319511abd5ce2c6e20f51c31",
                "address": "13.36.138.187:27146"
            },
            {
                "id": "107d49ada5acf1dbfcc27b3f5f387d035421ccca",
                "address": "52.214.221.72:27146"
            },
            {
                "id": "ca15ae8f0e17112b63786482cca300ff473f41fd",
                "address": "3.140.128.35:27146"
            },
            {
                "id": "5e89caf0ca79e0fb3371d5892efd96d66042d0d6",
                "address": "157.90.34.75:27146"
            },
            {
                "id": "1c88aa9509832a592453bd7d30736db055a279d1",
                "address": "34.83.232.180:27146"
            },
            {
                "id": "de7c36a34d8e9a48106488de1bac21b172c2dd49",
                "address": "157.245.16.34:27146"
            },
            {
                "id": "3de5f5bff746dc9349b044d83ccb906924b8cf03",
                "address": "188.166.138.88:27146"
            },
            {
                "id": "3ede6d36ede3b7e1dec522c827ab6db94bfae749",
                "address": "34.145.160.5:27146"
            },
            {
                "id": "58a28719fdd46ea629859d85a1d5bc6a6363c185",
                "address": "159.65.212.234:27146"
            },
            {
                "id": "70dd6252ff95d8af7f3f488fdb98dde5d467213b",
                "address": "18.117.49.201:27146"
            },
            {
                "id": "6c7d780bb7384142f6943543ed4c3ba537f4a411",
                "address": "138.197.59.244:27146"
            },
            {
                "id": "523a3df9384190d1b30ff55d1783b4baed32165c",
                "address": "18.208.113.188:27146"
            },
            {
                "id": "c64b58f2498a29330e4927ba90dd6fb2955a7a56",
                "address": "159.89.210.106:27146"
            },
            {
                "id": "e592368bf73a32dbcc28def417f2fdb151f26da6",
                "address": "3.139.117.117:27146"
            },
            {
                "id": "19ab508b32a6518a450058c2c7a99b7a5cc4299f",
                "address": "13.237.27.250:27146"
            },
            {
                "id": "4e41bd4f8d1ec95ff4a305f0739c82e818664c12",
                "address": "135.181.58.7:27146"
            },
            {
                "id": "2d25606076036716a31611185d39880fe8237e97",
                "address": "3.230.67.253:27146"
            },
            {
                "id": "5a6e66f9f6c84d55de8f1170086f28d69d242ad4",
                "address": "78.141.210.66:27146"
            },
            {
                "id": "f296c1e1b03ab875925208aabb5b9c5b1626427e",
                "address": "52.32.91.52:27146"
            }
        ]
    },
    "apis": {
        "rpc": [
            {
                "address": "https://rpc.thorchain.info",
                "provider": "thorchain"
            }
        ],
        "rest": [
            {
                "address": "https://thornode.thorchain.info",
                "provider": "thorchain"
            }
        ],
        "sidechains_rpc": [
            {
                "address": "https://btc.thorchain.info",
                "provider": "btc"
            },
            {
                "address": "https://bch.thorchain.info",
                "provider": "bch"
            },
            {
                "address": "https://ltc.thorchain.info",
                "provider": "ltc"
            },
            {
                "address": "https://bnb.thorchain.info",
                "provider": "bnb"
            },
            {
                "address": "https://eth.thorchain.info",
                "provider": "eth"
            }
        ]
    },
    "explorers": [
        {
            "kind": "THORChain explorer",
            "url": "https://thorchain.net",
            "tx_page": "https://thorchain.net/#/txs/${txHash}"
        },
        {
            "kind": "viewblock",
            "url": "https://viewblock.io/thorchain",
            "tx_page": "https://viewblock.io/thorchain/tx/${txHash}"
        }
    ]
}
